### PR TITLE
LAE EngineIgnitor

### PR DESCRIPTION
**Pull request by mountainparrot**

### CODE REVIEW

**Comment by zorg2044** [comment]
Thanks!

**Comment by SofieBrink** [comment]
Uhm, i'm not so sure about this one. I feel like it most definitely needs a `:NEEDS[]` clause for something other than BCS. whatever this may be providing for

**Comment by SofieBrink** [comment]
These modules will now be attempted to get added automagically which feels wrong because as far as i am aware those modules are not stock

**Comment by zorg2044** [comment]
Should be fixed here d8ba74a8ef1e9f6fe502e7cba7a5c26b890c2fc8

**Pull request merged**
